version: '1.0.1'
services:
  asterix:
    image: asterixnetwork/asterix:v1.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--chain', '/node/cli/src/celestial_testnet-raw.json', '--name', 'docker_compose_mainnet', '--ws-external', '--rpc-external', '--rpc-cors', 'all' ]
